- name: Install python-pip
  yum: name=python-pip state=latest

- stat: path=/usr/bin/curator
  register: p

- name: Install Curator with pip
  shell: "pip install elasticsearch-curator"
  when: p.stat.exists == False
  environment: 
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"    


# Kann sein das der ES Server noch nicht oben ist
- name: Get created Repos
  shell: es_repo_mgr --host {{ inventory_hostname }} show
  register: repomgr_result
  ignore_errors: yes

- debug: "msg={{ repomgr_result | to_nice_json }}"

- name: Create Backup Repository
  shell: es_repo_mgr --host {{ inventory_hostname }} create fs --repository backup --location {{ backup_repository_path }}
  when: ("backup" not in repomgr_result.stdout_lines and repomgr_result == true)
